version: '3'
services:
  db:
    container_name: postgres-link-shorten
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: trpc
      POSTGRES_PASSWORD: trpc
      POSTGRES_DB: trpc
    volumes: 
      - .dbdata:/var/lib/postgres 
    expose:
      - 5432
